---
- name: Deploy the act app
  hosts: web
  roles:
    - name: act.yarn
      tags: yarn
  become: yes
  vars:
    api: "{{hostvars[inventory_hostname]['mount']}}/act/api"
    couchdb: "{{hostvars[inventory_hostname]['mount']}}/act/couchdb"
    postgres: "{{hostvars[inventory_hostname]['mount']}}/act/postgres"
    keycloak: "{{hostvars[inventory_hostname]['mount']}}/act/keycloak"
  tasks:
    - name: Create directories for act app
      file: path=/{{item}} state=directory
      with_items:
        - ['{{couchdb}}/data', '{{postgres}}/data', '{{api}}/src']
      tags: act-folders
    - name: Checkout act src files
      git:
        repo: 'git://github.com/joe307bad/act.git'
        dest: '{{api}}/src/'
        force: yes
      tags: act-src
    - name: Copy up .env.prod
      copy:
        src: ../.env.prod
        dest: '{{api}}/src/deploy/.env'
      tags: act-env
    - name: Copy up docker-compose
      copy:
        src: ../docker-compose.yml
        dest: '{{api}}/src/deploy/docker-compose.yml'
      tags: act-copy-docker-compose
    - name: Copy up Dockerfile
      copy:
        src: ../Dockerfile
        dest: '{{api}}/src/deploy/Dockerfile'
      tags: act-copy-Dockerfile
    - name: Install API packages
      community.general.yarn:
        path: '{{api}}/src'
      tags: act-yarn-install
    - name: Build API dist
      ansible.builtin.command: 'yarn build:api'
      args:
        chdir: '{{api}}/src'
      tags: act-build-api
    - name: Start the act app
      docker_compose:
        project_src: '{{api}}/src/deploy'
        restarted: yes
        state: present
      tags: act-up
