version: '2'
services:
  act:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      args:
        - ACT_SRC=${ACT_SRC}
    environment:
      - COUCH_DB_URL=${COUCH_DB_URL}
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PW}
    ports:
      - '80:3333'
  couchdb:
    image: couchdb
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PW}
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    volumes:
      - '${COUCHDB_DATA}:/bitnami/couchdb'
      - ./couchdb.ini:/opt/couchdb/etc/local.d/couchdb.ini
  postgres:
    image: postgres
    volumes:
      - '${POSTGRES_DATA}:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: ${POSTGRES_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres
